feat: Add the EnforceCache
casbin/SwiftCasbin pull request #22
Opened 2021-06-18 14:52 UTC by captt-g

2021-06-19 01:49 UTC, hsluoyz commented
@xiaobeiswift

2021-06-19 02:55 UTC, xiaobeiswift approved these changes

2021-06-19 14:29 UTC, hsluoyz requested changes

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/APi/ManagementApi.swift
> +        model.getValuesForFieldInPolicy(sec: "p", ptype: ptype, fieldIndex: model.getModel()["p"]?["p"]?.tokens.firstIndex(of: "p_obj") ??  1)
Why?

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/APi/ManagementApi.swift
> +        model.getValuesForFieldInPolicy(sec: "p", ptype: ptype, fieldIndex: model.getModel()["p"]?["p"]?.tokens.firstIndex(of: "p_act") ??  2)
Why?

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/Core/Core.swift
> +import NIOConcurrencyHelpers
No new lines?

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/Core/Core.swift
> +            var locks: Locks
You should setup a good linter.

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/Enforce+Cache.swift
> +//
No header.

2021-06-19 14:29 UTC, hsluoyz commented on Sources/Casbin/Event.swift
> +func clearCache<T:CoreApi>(eventData:EventData,e: T) {
?

2021-06-23 05:17 UTC, hsluoyz approved these changes

2021-06-23 05:17 UTC, merged

2021-06-23 05:19 UTC, hsluoyz commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/casbin/SwiftCasbin/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: