feat: add globmatch
casbin/SwiftCasbin pull request #25
Opened 2021-12-13 08:17 UTC by feloraaa

Signed-off-by: feloraaa <704596810@qq.com>

2021-12-13 10:30 UTC, hsluoyz commented
@xiaobeiswift plz review

2021-12-18 12:56 UTC, hsluoyz commented
@meekotherogue plz review

2021-12-21 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/SwiftCasbin?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/SwiftCasbin?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/SwiftCasbin?pullRequest=25) it.</sub>

2021-12-21 17:01 UTC, meekotherogue requested changes

2021-12-21 17:01 UTC, meekotherogue commented on Tests/CasbinTests/UtilsTests/KeyMatchTests.swift
> +    }
I don't believe these tests are comprehensive. If you check out the Go implementation (which is a production ready library, and [given the docs I think is meant to be the source of truth for these matcher functions](https://casbin.org/docs/en/function#:~:text=See%20details%20for%20above%20functions%20at%3A)) there are many more tests: https://github.com/casbin/casbin/blob/master/util/builtin_operators_test.go#L454

If you adapt these tests into this test case, 8 will fail and 2 will error. This is indicative that there is not feature parity with other globMatch implementations.

```suggestion
    func testglobMatch() {
        XCTAssertTrue(Util.globMatch("/foo", "/foo"))
        XCTAssertTrue(Util.globMatch("/foo", "/foo*"))
        XCTAssertFalse(Util.globMatch("/foo", "/foo/*"))
        XCTAssertFalse(Util.globMatch("/foo/bar", "/foo"))
        XCTAssertFalse(Util.globMatch("/foo/bar", "/foo*"))
        XCTAssertTrue(Util.globMatch("/foo/bar", "/foo/*"))
        XCTAssertFalse(Util.globMatch("/foobar", "/foo"))
        XCTAssertTrue(Util.globMatch("/foobar", "/foo*"))
        XCTAssertFalse(Util.globMatch("/foobar", "/foo/*"))

        XCTAssertTrue(Util.globMatch("/foo", "*/foo"))
        XCTAssertTrue(Util.globMatch("/foo", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/foo", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/foo/bar", "*/foo"))
        XCTAssertFalse(Util.globMatch("/foo/bar", "*/foo*"))
        XCTAssertTrue(Util.globMatch("/foo/bar", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/foobar", "*/foo"))
        XCTAssertTrue(Util.globMatch("/foobar", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/foobar", "*/foo/*"))

        XCTAssertFalse(Util.globMatch("/prefix/foo", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/foo", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/foo", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/prefix/foo/bar", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/foo/bar", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/foo/bar", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/prefix/foobar", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/foobar", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/foobar", "*/foo/*"))

        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo/bar", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo/bar", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foo/bar", "*/foo/*"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foobar", "*/foo"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foobar", "*/foo*"))
        XCTAssertFalse(Util.globMatch("/prefix/subprefix/foobar", "*/foo/*"))
    }
```

I am not a maintainer, so it's up to them in the end if this is acceptable or not. But given that my team is using multiple different Casbin libraries - including the Swift one - I feel strongly that we should be able to expect similar behaviour across the libraries that we're using,.

2022-01-16 09:49 UTC, hsluoyz commented on Tests/CasbinTests/UtilsTests/KeyMatchTests.swift
> +    }
@feloraaa

2022-01-21 01:10 UTC, hsluoyz commented
Replaced by: https://github.com/casbin/SwiftCasbin/pull/26

2022-01-21 01:10 UTC, closed without merging